#!/usr/bin/env python3
"""Export the processed LaTeX project for manual editorial editing.

This script reuses the same preparation steps as the PDF exporter, but stops
after producing the final LaTeX build directory. The exported files are build
artifacts, not the source of truth for the TeachBook.
"""

from __future__ import annotations

import argparse
import io
import os
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

import export_pdf
from collect_used_bibliography import BibliographyError


PROJECT_ROOT = Path(__file__).resolve().parents[1]
BOOK_DIR = PROJECT_ROOT / "book"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "latex_exports"
IMAGE_ASSET_EXTENSIONS = {".gif", ".jpeg", ".jpg", ".pdf", ".png", ".svg"}


def force_utf8_stdio() -> None:
    for stream_name in ("stdout", "stderr"):
        stream = getattr(sys, stream_name)
        if stream.encoding and stream.encoding.lower() in {"utf-8", "utf8"}:
            continue
        wrapped = io.TextIOWrapper(stream.buffer, encoding="utf-8", errors="replace")
        setattr(sys, stream_name, wrapped)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Export the complete processed LaTeX project for one or more "
            "TeachBook languages."
        )
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Output directory for the editable LaTeX project (default: latex_exports).",
    )
    parser.add_argument(
        "--lang",
        action="append",
        default=None,
        help="Language code to export. Repeat for multiple languages. Defaults to all.",
    )
    parser.add_argument(
        "--keep-temp",
        action="store_true",
        help="Keep temporary _temp_latex_<lang> folders for debugging.",
    )
    parser.add_argument(
        "--no-zip",
        action="store_true",
        help="Do not create Overleaf-ready ZIP files.",
    )
    parser.add_argument(
        "--quick-validate",
        action="store_true",
        help="Validate existing exported folders/ZIPs without rebuilding them.",
    )
    return parser.parse_args()


def copy_templates(lang: str, latex_build_dir: Path) -> None:
    templates_root = PROJECT_ROOT / "latex_templates"

    export_pdf.generate_metadata_tex(lang, str(latex_build_dir))
    export_pdf.copy_root_latex_support_files(str(latex_build_dir))

    common_dir = templates_root / "common"
    if common_dir.exists():
        print("   Aplicando plantillas comunes (latex_templates/common)...")
        for item in common_dir.iterdir():
            if item.is_file():
                shutil.copy2(item, latex_build_dir / item.name)

    lang_dir = templates_root / lang
    if lang_dir.exists():
        print(f"   Aplicando plantillas para '{lang}' (latex_templates/{lang})...")
        for item in lang_dir.iterdir():
            if item.is_file():
                shutil.copy2(item, latex_build_dir / item.name)


def write_overleaf_helpers(lang_output: Path, main_tex: str) -> None:
    """Add small helper files that make Overleaf import less ambiguous."""
    if not main_tex:
        return

    wrapper = (
        "% Overleaf entry point generated by scripts/export_latex_project.py.\n"
        f"% The full Jupyter Book LaTeX file is {main_tex}.\n"
        f"\\input{{{main_tex}}}\n"
    )
    (lang_output / "main.tex").write_text(wrapper, encoding="utf-8", newline="\n")

    note = f"""# Overleaf import

Recommended Overleaf settings:

- Main document: `main.tex`
- Compiler: `XeLaTeX`

The full generated book file is `{main_tex}`. Edit `main.tex` only if you want
to change the entry point; for content-level final tweaks, edit `{main_tex}`.

Figures and graphic assets are stored in `assets/images/`. The exported LaTeX
files already reference those paths.

This folder is an exported artifact for final editorial work. The source of
truth for the TeachBook remains the `book/` directory in the original project.
If you regenerate this export, manual edits made here can be overwritten.
"""
    (lang_output / "OVERLEAF.md").write_text(note, encoding="utf-8", newline="\n")


def create_overleaf_zip(lang: str, lang_output: Path, output_dir: Path) -> Path:
    """Create a ZIP whose root is the LaTeX project, ready for Overleaf upload."""
    zip_path = output_dir / f"teachbook_{lang}_overleaf.zip"
    if zip_path.exists():
        zip_path.unlink()

    with zipfile.ZipFile(zip_path, mode="w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(lang_output.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(lang_output).as_posix())
    return zip_path


def latex_escape_path(path: str) -> str:
    """Escape path characters used in simple LaTeX macro arguments."""
    return path.replace("_", r"\_")


def rewrite_asset_paths_in_tex(lang_output: Path, moved_assets: dict[str, str]) -> None:
    """Rewrite LaTeX references after moving root-level assets into assets/."""
    if not moved_assets:
        return

    for tex_path in sorted(lang_output.glob("*.tex")):
        text = tex_path.read_text(encoding="utf-8")
        updated = text
        for old_name, new_name in moved_assets.items():
            old_path = Path(old_name)
            new_path = Path(new_name)

            old_sphinx = "{{" + old_path.stem + "}" + old_path.suffix + "}"
            new_sphinx = (
                "{{" + new_path.with_suffix("").as_posix() + "}" + new_path.suffix + "}"
            )
            updated = updated.replace(old_sphinx, new_sphinx)

            updated = updated.replace("{" + old_name + "}", "{" + new_name + "}")
            updated = updated.replace(
                "{" + latex_escape_path(old_name) + "}",
                "{" + latex_escape_path(new_name) + "}",
            )

        if updated != text:
            tex_path.write_text(updated, encoding="utf-8", newline="\n")


def organize_exported_assets(lang_output: Path) -> None:
    """Move exported figure/media assets into predictable folders."""
    assets_dir = lang_output / "assets"
    images_dir = assets_dir / "images"
    support_dir = assets_dir / "support"
    images_dir.mkdir(parents=True, exist_ok=True)

    moved_assets: dict[str, str] = {}
    for path in sorted(lang_output.iterdir()):
        if not path.is_file() or path.suffix.lower() not in IMAGE_ASSET_EXTENSIONS:
            continue
        target = images_dir / path.name
        if target.exists():
            target.unlink()
        shutil.move(str(path), str(target))
        moved_assets[path.name] = target.relative_to(lang_output).as_posix()

    rewrite_asset_paths_in_tex(lang_output, moved_assets)

    for path in sorted(lang_output.iterdir()):
        if not path.is_dir() or not path.name.startswith("_"):
            continue
        support_dir.mkdir(parents=True, exist_ok=True)
        target = support_dir / path.name
        if target.exists():
            shutil.rmtree(target)
        shutil.move(str(path), str(target))

    if moved_assets:
        print(
            f"Assets graficos organizados en {images_dir.relative_to(lang_output)} "
            f"({len(moved_assets)} archivo(s))."
        )


def read_cover_image_path(lang_output: Path) -> str:
    metadata_path = lang_output / "bookmetadata.tex"
    if not metadata_path.exists():
        return ""
    for line in metadata_path.read_text(encoding="utf-8").splitlines():
        marker = r"\renewcommand{\BookCoverImage}{"
        if marker not in line:
            continue
        value = line.split(marker, 1)[1].rsplit("}", 1)[0]
        return value.replace(r"\_", "_")
    return ""


def validate_exported_project(lang: str, output_dir: Path) -> bool:
    """Validate that an existing export contains the files Overleaf needs."""
    lang_output = output_dir / lang
    zip_path = output_dir / f"teachbook_{lang}_overleaf.zip"
    images_dir = lang_output / "assets" / "images"
    required_files = {
        "main.tex",
        "projectnamenotset.tex",
        "bookmetadata.tex",
        "jupyterBook.cls",
        "language_support.tex",
        "latexmkrc",
        "OVERLEAF.md",
    }

    ok = True
    if not lang_output.exists():
        print(f"ERROR: no existe la carpeta exportada: {lang_output}")
        ok = False
    else:
        for name in sorted(required_files):
            if not (lang_output / name).exists():
                print(f"ERROR: falta {name} en {lang_output}")
                ok = False
        if not images_dir.exists():
            print(f"ERROR: falta la carpeta de assets graficos: {images_dir}")
            ok = False
        root_images = [
            path.name
            for path in sorted(lang_output.iterdir())
            if path.is_file() and path.suffix.lower() in IMAGE_ASSET_EXTENSIONS
        ]
        if root_images:
            print(
                "ERROR: quedan assets graficos en la raiz de la exportacion: "
                + ", ".join(root_images[:10])
            )
            ok = False
        cover_image = read_cover_image_path(lang_output)
        if cover_image and not (lang_output / cover_image).exists():
            print(f"ERROR: la imagen de portada no existe: {cover_image}")
            ok = False

    if not zip_path.exists():
        print(f"ERROR: no existe el ZIP para Overleaf: {zip_path}")
        return False

    try:
        with zipfile.ZipFile(zip_path) as archive:
            names = set(archive.namelist())
    except zipfile.BadZipFile:
        print(f"ERROR: ZIP no valido: {zip_path}")
        return False

    for name in sorted(required_files):
        if name not in names:
            print(f"ERROR: falta {name} en {zip_path}")
            ok = False
    cover_image = read_cover_image_path(lang_output)
    if cover_image and cover_image not in names:
        print(f"ERROR: falta {cover_image} en {zip_path}")
        ok = False

    if ok:
        print(f"OK: exportacion LaTeX valida para {lang}: {zip_path}")
    return ok


def prepare_temp_project(lang: str, temp_root: Path) -> Path:
    if temp_root.exists():
        shutil.rmtree(temp_root)
    temp_root.mkdir(parents=True)

    if lang == "default":
        shutil.copytree(BOOK_DIR, temp_root, dirs_exist_ok=True)
        config_src = BOOK_DIR / "_config.yml"
        toc_src = BOOK_DIR / "_toc.yml"
    else:
        lang_src = BOOK_DIR / lang
        if not lang_src.exists():
            raise FileNotFoundError(f"No existe el contenido del idioma: {lang_src}")
        shutil.copytree(lang_src, temp_root / lang)

        static_src = BOOK_DIR / "_static"
        if static_src.exists():
            shutil.copytree(static_src, temp_root / "_static")

        config_src = BOOK_DIR / f"_config_{lang}.yml"
        toc_src = BOOK_DIR / f"_toc_{lang}.yml"

    config_dst = temp_root / "_config.yml"
    toc_dst = temp_root / "_toc.yml"
    shutil.copy2(config_src, config_dst)
    shutil.copy2(toc_src, toc_dst)

    export_pdf.sanitize_config(str(config_dst))
    export_pdf.prepare_bibliography_for_pdf(str(temp_root), lang, str(config_dst))
    export_pdf.rewrite_gif_references_for_pdf(str(temp_root), lang)
    export_pdf.sanitize_kroki_blocks_for_pdf(str(temp_root))
    return temp_root


def build_latex_project(lang: str, output_dir: Path, keep_temp: bool, make_zip: bool) -> bool:
    print(f"\nExportando proyecto LaTeX para: {lang.upper()}", flush=True)
    temp_root = PROJECT_ROOT / f"_temp_latex_{lang}"

    try:
        src_dir = prepare_temp_project(lang, temp_root)
    except (BibliographyError, RuntimeError, OSError) as exc:
        print(f"ERROR preparando el proyecto temporal para '{lang}':")
        print(exc)
        if temp_root.exists() and not keep_temp:
            shutil.rmtree(temp_root)
        return False

    build_dir = src_dir / "_build"
    latex_build_dir = build_dir / "latex"
    if build_dir.exists():
        shutil.rmtree(build_dir)

    jupyter_book = export_pdf.get_jupyter_book()
    if not jupyter_book:
        print("ERROR: no se encontro jupyter-book. Ejecuta scripts/setup_env.py.")
        return False

    print("Generando LaTeX con Jupyter Book...", flush=True)
    try:
        subprocess.run(
            [jupyter_book, "build", "--builder", "latex", str(src_dir), "--all"],
            shell=(os.name == "nt"),
            check=True,
        )
    except subprocess.CalledProcessError as exc:
        print(f"ERROR en jupyter-book build ({lang}): {exc}")
        if temp_root.exists() and not keep_temp:
            shutil.rmtree(temp_root)
        return False

    if not latex_build_dir.exists():
        print(f"ERROR: no se genero el directorio LaTeX: {latex_build_dir}")
        if temp_root.exists() and not keep_temp:
            shutil.rmtree(temp_root)
        return False

    print("Aplicando metadatos, plantillas y assets LaTeX-safe...", flush=True)
    copy_templates(lang, latex_build_dir)
    if not export_pdf.prepare_svg_images_for_latex(str(latex_build_dir)):
        if temp_root.exists() and not keep_temp:
            shutil.rmtree(temp_root)
        return False
    export_pdf.mirror_shared_asset_paths_for_latex(str(latex_build_dir))

    lang_output = output_dir / lang
    if lang_output.exists():
        shutil.rmtree(lang_output)
    lang_output.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(latex_build_dir, lang_output)
    organize_exported_assets(lang_output)

    tex_files = [
        path.name
        for path in sorted(lang_output.glob("*.tex"))
        if path.name not in {"bookmetadata.tex", "language_support.tex"}
    ]
    main_tex = "python.tex" if "python.tex" in tex_files else (tex_files[0] if tex_files else "")
    write_overleaf_helpers(lang_output, main_tex)

    print(f"Proyecto LaTeX exportado en: {lang_output}")
    if main_tex:
        print("Archivo principal para Overleaf: main.tex")
        print(f"Archivo completo generado: {main_tex}")
        print("Compilacion manual: latexmk -xelatex main.tex")

    if make_zip:
        zip_path = create_overleaf_zip(lang, lang_output, output_dir)
        print(f"ZIP listo para Overleaf: {zip_path}")

    if temp_root.exists() and not keep_temp:
        shutil.rmtree(temp_root)
    return True


def main() -> int:
    force_utf8_stdio()
    os.chdir(PROJECT_ROOT)
    args = parse_args()

    available_langs = export_pdf.get_languages()
    requested_langs = args.lang or available_langs
    unknown = sorted(set(requested_langs) - set(available_langs))
    if unknown:
        print(f"ERROR: idioma(s) no configurado(s): {', '.join(unknown)}")
        print(f"Idiomas disponibles: {', '.join(available_langs)}")
        return 1

    output_dir = args.output
    if not output_dir.is_absolute():
        output_dir = PROJECT_ROOT / output_dir

    if args.quick_validate:
        print("Validacion rapida de exportacion LaTeX", flush=True)
        print(f"Idiomas: {', '.join(requested_langs)}", flush=True)
        print(f"Salida: {output_dir}", flush=True)
        ok = all(validate_exported_project(lang, output_dir) for lang in requested_langs)
        return 0 if ok else 1

    print("Exportacion de proyecto LaTeX editable", flush=True)
    print(f"Idiomas: {', '.join(requested_langs)}", flush=True)
    print(f"Salida: {output_dir}", flush=True)
    print(
        "Nota: esta carpeta es un artefacto editable final; la fuente sigue en book/.",
        flush=True,
    )

    success_count = 0
    for lang in requested_langs:
        if build_latex_project(
            lang,
            output_dir,
            keep_temp=args.keep_temp,
            make_zip=not args.no_zip,
        ):
            success_count += 1

    if success_count == len(requested_langs):
        print(f"\nOK: {success_count} proyecto(s) LaTeX exportado(s).")
        return 0

    print(f"\nERROR: se exportaron {success_count} de {len(requested_langs)} proyecto(s).")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
